version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "discussion-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ogwcxims2htx"
s3_prefix = "discussion-app"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
